#!/bin/bash
# Use this script for training NNs in batch
# Passing arguments to main: 
#$1: Test or Train
#$2: # Leaders
#$3: # Robots
#$4: # Epocs
#$5: # Experiment ID
#$6: Communication Model (Not Supported)

# Compiling and running code is separate now! 
# Don't forget to run ./compile before running this code, if you make changes to the code.

echo Batch Training Initialized...

for i in {1..10}; do
	echo TRAINING $i out of 10 networks...
	echo 4 leaders, 10 robots
    ./bin/main "TRAIN" 4 10 100 $i
done

#for i in {6..30..4}; do
#	echo TRAINING $i robots, 4 leaders
#    ./bin/main "TRAIN" 4 $i 100 
#done

#for i in {10..30..4}; do
#	echo TRAINING $i robots, 8 leaders
#    ./bin/main "TRAIN" 8 $i 100 
#done
