#!/bin/bash
# Use this script for statistical data collection
# $1 -> Statistical Run Count
# Compiling and running code is separate now! 
# Don't forget to run ./compile before running this code, if you make changes to the code.

echo Batch Training Initialized...

R=20
for ((l=0;l<=20;l+=4)) do 			# Varying leader count
	echo $l leaders, $R robots
	for ((i=0;i<$1;i++)) do 		# Statistical Runs
		echo TRAINING $i out of $1 networks...
	    ./bin/main "TRAIN" $l 20 75 $i
	done
done

#for i in {6..30..4}; do
#	echo TRAINING $i robots, 4 leaders
#    ./bin/main "TRAIN" 4 $i 100 
#done

#for i in {10..30..4}; do
#	echo TRAINING $i robots, 8 leaders
#    ./bin/main "TRAIN" 8 $i 100 
#done
